### ISSUE TITLE
歌词无法自动滚动

### ISSUE THREAD

**Issue by quantmod** [qibin0506/LitePlayer#1]
这位大哥我歌词显示了，可是并没有随着音乐的播放而自动切换，请问歌词格式有啥要求吗

**Comment by qibin0506** [comment]
看[https://github.com/qibin0506/LitePlayer/blob/master/LitePlayer/src/org/loader/liteplayer/PlayActivity.java](https://github.com/qibin0506/LitePlayer/blob/master/LitePlayer/src/org/loader/liteplayer/PlayActivity.java) 第276行

**Comment by quantmod** [comment]
不知道什么原因，我换了个低版本的android4.1的手机就好了，原先在android 5.0的机器上播放时歌词确实不随着歌曲滚动
